<?php
/**
 * Edit Category page view
 *
 * Страница добавление/ редактирования категорий системы тестирования
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_CATEGORIES]'));
?>

<div id="main">
    <div class="menu-h f-right">
	    <ul>
	        <li><a href="<?=$this->url(array('controller' => 'index', 'action' => 'index'), null, true)?>">Главная</a></li>
	        <li><a href="<?=$this->url(array('controller' => 'test', 'action' => 'index'), null, true)?>">Тесты</a></li>
	        <li><a href="<?=$this->url(array('controller' => 'category', 'action' => 'index'), null, true)?>">Категории тестов</a></li>
	    </ul>
    </div>
	<h1 class="title" style="display:inline; border:0">Категории : добавление/редактирование</h1>
    <?php echo $this -> objCategoryEditForm; ?>
</div>
