<?php
/**
 * Index Applicant page view
 *
 * Страница соискателей
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_APPLICANTS]'));
?>

<div id="main">

    <div id="filter-form">
        <?php echo $this -> objFilterForm; ?>
    </div>
	<!-- Таблица соискателей -->
	<table width="100%" border="1" cellpadding="0" cellspacing="0" id="tableApplicants" class="tablesorter">
    <thead>
		<tr>
		    <th>№</th>
		    <th>Фамилия Имя Отчество</th>
		    <th>Дата рождения</th>
		    <th class=''>Должность / вакансия</th>
		    <th>Электроннай почта</th>
		    <th>Контактный номер</th>
		    <th>Статус</th>
		    <th>Действия</th>
		</tr>
    </thead>
    <tbody>

    <?php if (!empty($this -> arrApplicants)): ?>
        <?php foreach ($this -> arrApplicants as $applicant): ?>
        <tr>
			<td><?php echo $this->escape( $applicant -> id ); ?></td>
			<td>
			    <a href="<?php echo $this -> url ( array (
				'controller' => 'applicant',
				'action' => 'show',
				'applicantId' => $applicant->id
			    ) ); ?>">
				<?php echo $this->escape( $applicant -> last_name ); ?>
				<?php echo $this->escape( $applicant -> name ); ?>
				<?php echo $this->escape( $applicant -> patronymic ); ?>
			    </a>
			</td>
			<td><?php echo $this->toDate( $applicant-> birth ); ?></td>
			<td><?php echo $this->escape( $applicant -> v_name ); ?></td>
			<td><?php echo $this->escape( $applicant -> email ); ?></td>
			<td><?php echo $this->escape( $applicant -> phone ); ?></td>
			<td>
    			    <a href="<?php echo $this -> url ( array (
				'controller' => 'applicant',
				'action' => 'status',
				'applicantId' => $applicant->id
			    ) ); ?>">
				<?php echo $this->translate('[LS_STATUS_' . strtoupper($this->escape( $applicant -> status )) . ']'); ?>
			    </a>
			</td>
			<td>
				<a href="<?php echo $this -> url ( array ( 'controller' => 'applicant', 'action' => 'edit', 'applicantId' => $applicant->id) ); ?>"><?php echo $this->translate('[LS_LINK_EDIT]'); ?></a><br />
				<a href="<?php echo $this -> url ( array ( 'controller' => 'applicant', 'action' => 'remove', 'applicantId' => $applicant->id) ); ?>" onClick="return confirm('<?php echo $this->translate('[LS_LINK_REMOVE_CONFIRMATION]'); ?> \' <?php echo $this->escape( $applicant->t_name ); ?>\'');"><?php echo $this->translate('[LS_LINK_REMOVE]'); ?></a><br />
			</td>
		</tr>
	    <?php endforeach; ?>
    <?php else: ?>
    	<tr>
			<td></td>
			<td colspan="6">
			    нет соискателей
			</td>
			<td>&nbsp;</td>
		</tr>
    <?php endif;?>
	</tbody>
	</table>
	<!-- End of Таблица тестов-->
</div>