<?php
/**
 * Index Applicant page view
 *
 * Страница информации о соискателе
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_APPLICANTS]'));
$this->headTitle($this->translate('[LS_PAGE_TITLE_APPLICANTS_INFO]'));
?>

<div id="main">
    <?php if (!empty($this -> applicant)): ?>
	<h1>
	    <?php echo $this->escape( $this -> applicant -> last_name ); ?>
	    <?php echo $this->escape( $this -> applicant -> name ); ?>
	    <?php echo $this->escape( $this -> applicant -> patronymic ); ?>
	</h1>
<table border="1" width="500px;">
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_LASTNAME_LABEL]' ); ?></td>
	<td><?php echo $this->escape( $this->applicant->getLastName() ); ?></td>
	<td rowspan="7">
	    <?php if ($this -> applicant -> getPhoto() != ''): ?>
	    <img src="<?php echo $this -> applicant -> getPhoto(); ?>" height="100">
	    <?php endif; ?>
	    <?php
		if ($this -> applicant -> getNumber() != 0) {
		    echo $this->translate( '[LS_FORM_EDIT_NUMBER_LABEL]' ) . ': ';
		    echo $this->escape( $this->applicant->getNumber() );
		}
	    ?>
	</td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_NAME_LABEL]' ); ?></td>
	<td><?php echo $this->escape( $this->applicant->getName() ); ?></td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_PATRONYMIC_LABEL]' ); ?></td>
	<td><?php echo $this->escape( $this->applicant->getPatronymic() ); ?></td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_BIRTH_LABEL]' ); ?></td>
	<td><?php echo $this->toDate( $this->applicant->getBirth() ); ?></td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_VACANCY_LABEL]' ); ?></td>
	<td><?php echo $this->escape( $this->applicant->getVacancyId() ); ?></td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_EMAIL_LABEL]' ); ?></td>
	<td>
	    <a href="mailto:<?php echo $this->escape( $this->applicant->getEmail() ); ?>">
	        <?php echo $this->escape( $this->applicant->getEmail() ); ?>
	    </a>
	</td>
    </tr>
    <tr>
	<td><?php echo $this->translate( '[LS_FORM_EDIT_PHONE_LABEL]' ); ?></td>
	<td><?php echo $this->escape( $this->applicant->getPhone() ); ?></td>
    </tr>
</table>
<div class="resume">
    <strong><?php echo $this->translate( '[LS_FORM_EDIT_RESUME_LABEL]' ); ?></strong><br>
    <?php echo $this->special($this->applicant->getResume()); ?>
</div>
<strong>Комментарии</strong>
    <?php if (!empty($this -> comments)): ?>
	<table border="0" width="500px">
        <?php foreach ($this -> comments as $comment): ?>
	    <tr>
		<td><?php echo $this->escape( $comment -> nickname ); ?></td>
		<td align="right"><?php echo $this->toDate( $comment -> c_date, true ); ?></td>
	    </tr>
	    <tr>
		<td colspan="2" style="padding-bottom: 10px; border-bottom: dotted thin;">
		    <?php echo $comment -> c_comment ?>
		</td>
	    </tr>
	<?php endforeach; ?>
	</table>
    <?php endif; ?>
    
    <?php if (!empty($this -> commentForm)): ?>
    <?php echo $this -> commentForm ?>
    <?php endif; ?>
    

    <?php else: ?>
	не найден
    <?php endif;?>
</div>