<?php
/**
 * Index Test page view
 *
 * Страница категорий системы тестирования
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_CATEGORIES]'));
?>

<div id="main">
    <div style="clear:both; margin-bottom:10px; border-top:2px solid #123466"></div>
    <ul class="menu" style="float:right">
        <li style="display:inline"><a href="/index.php">Главная</a></li>
        <li style="display:inline"><a href="/index.php/test">Тесты</a></li>
        <li style="display:inline"><a href="/index.php/category/edit">Добавить категорию</a></li>
    </ul>
    <div style="clear:both; margin-bottom:10px; border-top:2px solid #123466"></div>
	<h1 class="title" style="display:inline; border:0">Категории : </h1>
    <div style="clear:both; margin-bottom:10px; border-top:2px solid #123466"></div>
	<!-- Таблица категорий -->
	<table width="100%" border="1" cellpadding="0" cellspacing="0">
		<tr class="head">
			<td>№</td>
			<td>Категория</td>
			<td>Комментарии</td>
			<td class="action">Действия</td>
		</tr>
<?php if (!empty($this -> arrCategory)): ?>
    <?php foreach ($this -> arrCategory as $category): ?>
		<tr class="item_row">
            <td><?php echo $this->escape( $category['cat_id'] ); ?></td>
			<td><?php echo $this->escape( $category['cat_name'] ); ?></td>
			<td><?php echo $this->escape( $category['cat_descr'] ); ?></td>
			<td class="action">
                <a href="<?php echo $this -> url ( array ( 'controller' => 'category', 'action' => 'edit', 'categoryId' => $category['cat_id']) ); ?>"><?php echo $this->translate('[LS_LINK_EDIT]'); ?></a><br />
                <a href="<?php echo $this -> url ( array ( 'controller' => 'category', 'action' => 'remove', 'categoryId' => $category['cat_id']) ); ?>" onClick="return confirm('<?php echo $this->translate('[LS_LINK_REMOVE_CONFIRMATION]'); ?> \' <?php echo $this->escape( $category['cat_name'] ); ?>\'');"><?php echo $this->translate('[LS_LINK_REMOVE]'); ?></a><br />
			</td>
		</tr>
    <?php endforeach; ?>
<?php else: ?>
		<tr class="item_row">
			<td></td>
			<td colspan="5">нет категорий</td>
		</tr>
<?php endif;?>
	</table>
	<!-- End of Таблица тестов-->
</div>