<?php
/**
 * Форма напоминания пароля
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_USER_FORGETPASSWORD]'));
?>
<?php if(count($this->form->getErrorMessages())):?>
    <div class="error">
        <?php echo implode(';',$this->form->getErrorMessages()); ?>
    </div>
<?php endif;?>
<div id="forget_password_form">
    <?php echo $this->form; ?>
</div>