<?php
/**
 * Оповещение об отправке ссылки для напоминания
 *
 * При успешной отправке ссылки для сброса пароля на email пользователь попадает на эту страницу
 *  
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_USER_FORGETPASSWORD_SUCCESS]'));
?>
<div class="message">
    <?php echo $this->translate('[LS_FORGETPASSWORD_SUCCESS]'); ?>
</div>
