<?php
/**
 * Вид письма напоминания (HTML)
 * 
 * HTML-письмо с ссылкой обновления пароля (если забыли)
 *
 * @package zfhrtool
 * @subpackage View
 */
?>
Здравствуйте <?php echo $this->nickname; ?>,!<br />
<br />
Кто-то (Возможно Вы) пытается восстановить пароль.<br />
Для восстановления пароля перейдите по этой ссылке:<br />
<br />
<?php echo 'http://' . $this->host . $this->url(array('controller'=>'user','action'=>'recover-password','id'=>$this->id,'code'=>$this->code),'default',true); ?><br />
<br />
Если Вы не желаете менять пароль, просто проигнорируйте это письмо.<br />
<br />
<br />
С уважением,<br />
&nbsp;&nbsp;&nbsp;&nbsp;Администрация сайта.<br />