<?php
/**
 * Главный слой
 *
 * @package zfhrtool
 * @subpackage View
 */

$this->headLink()->appendStylesheet("/styles/main.css");
$this->headLink()->appendStylesheet("/styles/tablesorter.css");

$this->headScript()->appendScript('
    function subm(href) {
        document.getElementById("AFF").action = href;
        document.getElementById("vacancyId").form.submit();
        return false;
    }
');
echo $this->doctype(),PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headTitle()?>
    <?= $this->headLink() ?>
    <?= $this->headScript(); ?>
<?php
    if ($this->dojo()->isEnabled()):
        $this->dojo()//->setLocalPath('/scripts/dojo/dojo/dojo.js')
            ->addStyleSheetModule('dijit.themes.tundra');
        echo $this->dojo();
    endif;
?>
</head>

<body class="tundra">
    <div class="menu-h-d">
        <?php echo $this->navigation()->menu(); ?>
    </div>
    <br><br>
    <div class="content">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>