<?php
/**
 * Edit Applicant page view
 *
 * Страница добавление/ редактирования соискателей
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_APPLICANTS]'));
$this->headTitle($this->translate('[LS_PAGE_TITLE_APPLICANTS_EDIT]'));
?>
<div id="main">
	<h1 class="title" style="display:inline; border:0">Добавление/редактирование соискателя</h1>
	<?php echo $this -> objForm; ?>
</div>