<?php
/**
 * Вид письма активации (HTML)
 * 
 * HTML-письмо с ссылкой активации зарегистрированной учетной записи
 *
 * @package zfhrtool
 * @subpackage View
 */
?>
Здравствуйте <?=$this->nickname?><br />
<br />
Вы успешно зарегистрировались в системе.
<br />
Для активации аккаунта перейдите по этой
<a href="<?php echo 'http://' . $this->host . $this->url(array('controller'=>'user','action'=>'activate','id'=>$this->id,'code'=>$this->code),'default',true); ?>">
    ссылке
</a>

<br />
Для доступа к аккаунту используйте следующую информацию:<br />
-----------------------------------------------<br />
Логин: <?=$this->login?><br />
Пароль:<?=$this->password?><br />