<?php
/**
 * Вид письма напоминания (Text)
 * 
 * Text-письмо с ссылкой обновления пароля (если забыли)
 *
 * @package zfhrtool
 * @subpackage View
 */
?>
Здравствуйте <?php echo $this->nickname; ?>,!

Кто-то (Возможно Вы) пытается восстановить пароль.
Для восстановления пароля перейдите по этой ссылке:
<?php echo 'http://' . $this->host . $this->url(array('controller'=>'user','action'=>'recover-password','id'=>$this->id,'code'=>$this->code),'default',true); ?>

Если Вы не желаете менять пароль, просто проигнорируйте это письмо.


С уважением,
&nbsp;&nbsp;&nbsp;&nbsp;Администрация сайта.