<?php
/**
 * Форма ввода нового пароля
 *
 * @package zfhrtool
 * @subpackage View
 */
$this->headTitle($this->translate('[LS_PAGE_TITLE_USER_CHANGEPASSWORD]'));
?>

<?php if (count($this->form->getErrorMessages())):?>
    <div class="error">
        <?php echo implode(';',$this->form->getErrorMessages()); ?>
    </div>
<?php endif;?>
<div id="recover_password_form">
    <?php echo $this->form; ?>
</div>